name: rag_env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - asttokens=2.0.5
  - blas=1.0
  - boost-cpp=1.82.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - cairo=1.16.0
  - certifi=2024.7.4
  - colorama=0.4.6
  - comm=0.2.1
  - cpuonly=2.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.6.2
  - filelock=3.13.1
  - fontconfig=2.14.1
  - freetype=2.12.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmpy2=2.1.2
  - html5lib=1.1
  - intel-openmp=2023.1.0
  - ipykernel=6.25.2
  - ipython=8.25.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - lcms2=2.12
  - lerc=3.0
  - libboost=1.82.0
  - libcurl=8.7.1
  - libdeflate=1.17
  - libffi=3.4.4
  - libglib=2.78.4
  - libiconv=1.16
  - libpng=1.6.39
  - libsodium=1.0.18
  - libssh2=1.11.0
  - libtiff=4.5.1
  - libuv=1.48.0
  - libxml2=2.13.1
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - nest-asyncio=1.6.0
  - openjpeg=2.5.2
  - openssl=3.0.14
  - parso=0.8.3
  - pcre2=10.42
  - pip=24.2
  - pixman=0.40.0
  - platformdirs=3.10.0
  - poppler=22.12.0
  - poppler-data=0.4.11
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - python=3.11.4
  - python-crfsuite=0.9.9
  - python-dateutil=2.9.0post0
  - pytorch=2.4.0
  - pytorch-mutex=1.0
  - pywin32=305
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - sympy=1.12
  - tbb=2021.8.0
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - vc=14.40
  - vs2015_runtime=14.40.33807
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - accelerate==0.31.0
      - aiofiles==23.2.1
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - altair==5.3.0
      - annotated-types==0.5.0
      - antlr4-python3-runtime==4.9.3
      - anyascii==0.3.2
      - anyio==4.4.0
      - asgiref==3.8.1
      - attrs==23.2.0
      - audioread==3.0.1
      - babel==2.16.0
      - backoff==2.2.1
      - bangla==0.0.2
      - bcrypt==4.1.3
      - beautifulsoup4==4.12.3
      - bitsandbytes==0.43.1
      - blinker==1.8.2
      - blis==0.7.10
      - bnnumerizer==0.0.2
      - bnunicodenormalizer==0.1.7
      - bpemb==0.3.4
      - build==1.2.1
      - cachetools==5.3.3
      - camelot-py==0.11.0
      - catalogue==2.0.9
      - cffi==1.17.0
      - chardet==5.2.0
      - chroma-hnswlib==0.7.3
      - chromadb==0.5.0
      - click==8.1.7
      - cmake==3.27.1
      - coloredlogs==15.0.1
      - confection==0.1.1
      - contourpy==1.1.1
      - coqpit==0.0.17
      - ctransformers==0.2.27
      - cycler==0.11.0
      - cymem==2.0.7
      - cython==3.0.0
      - dataclasses-json==0.6.6
      - dateparser==1.1.8
      - deepdiff==7.0.1
      - deprecated==1.2.14
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.6.1
      - docopt==0.6.2
      - effdet==0.4.1
      - einops==0.8.0
      - email-validator==2.1.1
      - emoji==2.8.0
      - en-core-web-lg==3.6.0
      - en-core-web-sm==3.6.0
      - en-core-web-trf==3.6.1
      - encodec==0.1.1
      - et-xmlfile==1.1.0
      - fastapi==0.115.6
      - fastapi-cli==0.0.4
      - ffmpy==0.3.2
      - filetype==1.2.0
      - flask==3.0.3
      - flatbuffers==24.3.25
      - fonttools==4.42.1
      - frozenlist==1.4.1
      - fsspec==2023.6.0
      - g2pkk==0.1.2
      - gensim==4.3.2
      - ghostscript==0.7
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-api-core==2.19.1
      - google-auth==2.29.0
      - google-cloud-vision==3.7.3
      - googleapis-common-protos==1.63.0
      - gpt4all==2.7.0
      - gradio==5.9.1
      - gradio-client==1.5.2
      - greenlet==3.0.3
      - grpcio==1.64.0
      - grpcio-status==1.62.2
      - gruut==2.2.3
      - gruut-ipa==0.13.0
      - gruut-lang-de==2.0.1
      - gruut-lang-en==2.0.1
      - gruut-lang-es==2.0.1
      - gruut-lang-fr==2.0.2
      - h11==0.14.0
      - hangul-romanize==0.1.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.27.0
      - humanfriendly==10.0
      - idna==3.7
      - importlib-metadata==7.0.0
      - importlib-resources==6.4.0
      - inflect==7.3.1
      - install==1.3.5
      - iopath==0.1.10
      - ipywidgets==8.1.0
      - itsdangerous==2.2.0
      - jamo==0.4.1
      - jieba==0.42.1
      - joblib==1.3.2
      - jpype1==1.5.0
      - jsonlines==1.2.0
      - jsonpatch==1.33
      - jsonpath-python==1.0.6
      - jsonpointer==2.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyterlab-widgets==3.0.8
      - kiwisolver==1.4.5
      - kubernetes==29.0.0
      - langchain==0.2.1
      - langchain-community==0.2.1
      - langchain-core==0.2.3
      - langchain-text-splitters==0.2.0
      - langcodes==3.3.0
      - langdetect==1.0.9
      - langfuse==2.48.0
      - langgraph==0.0.69
      - langsmith==0.1.65
      - layoutparser==0.3.4
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - llama-cpp-python==0.2.81
      - llvmlite==0.43.0
      - lxml==5.2.2
      - markdown==3.6
      - markdown-it-py==3.0.0
      - marshmallow==3.21.2
      - matplotlib==3.8.0
      - mdurl==0.1.2
      - mmh3==4.1.0
      - monotonic==1.6
      - more-itertools==10.4.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - murmurhash==1.0.9
      - mypy-extensions==1.0.0
      - ndg-httpsclient==0.5.1
      - networkx==2.8.8
      - ngrok==1.3.0
      - nltk==3.8.1
      - nuitka==2.3.9
      - num2words==0.5.13
      - numba==0.60.0
      - numpy==1.26.4
      - oauthlib==3.2.2
      - olefile==0.47
      - ollama==0.2.1
      - omegaconf==2.3.0
      - onnx==1.16.1
      - onnxruntime==1.18.0
      - openai-whisper==20231117
      - opencv-python==4.10.0.84
      - openpyxl==3.1.2
      - opentelemetry-api==1.24.0
      - opentelemetry-exporter-otlp-proto-common==1.24.0
      - opentelemetry-exporter-otlp-proto-grpc==1.24.0
      - opentelemetry-instrumentation==0.45b0
      - opentelemetry-instrumentation-asgi==0.45b0
      - opentelemetry-instrumentation-fastapi==0.45b0
      - opentelemetry-proto==1.24.0
      - opentelemetry-sdk==1.24.0
      - opentelemetry-semantic-conventions==0.45b0
      - opentelemetry-util-http==0.45b0
      - ordered-set==4.1.0
      - orjson==3.10.3
      - overrides==7.7.0
      - packaging==23.2
      - pandas==1.5.3
      - pathy==0.10.2
      - pdf2image==1.17.0
      - pdfminer-six==20231228
      - pdfplumber==0.11.2
      - pikepdf==9.0.0
      - pillow==10.0.0
      - pillow-heif==0.17.0
      - pipdeptree==2.12.0
      - pooch==1.8.2
      - portalocker==2.10.1
      - posthog==3.5.0
      - preshed==3.0.8
      - proto-plus==1.24.0
      - protobuf==4.25.3
      - py-cpuinfo==9.0.0
      - pyarrow==16.1.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycocotools==2.0.8
      - pycparser==2.22
      - pydantic==2.3.0
      - pydantic-core==2.6.3
      - pydeck==0.9.1
      - pydeps==1.12.13
      - pydub==0.25.1
      - pygtrie==2.5.0
      - pymupdf==1.24.7
      - pymupdfb==1.24.6
      - pyngrok==7.1.6
      - pynndescent==0.5.13
      - pypandoc==1.13
      - pyparsing==3.1.1
      - pypdf==4.2.0
      - pypdfium2==4.30.0
      - pypika==0.48.9
      - pypinyin==0.52.0
      - pyproject-hooks==1.1.0
      - pyreadline3==3.4.1
      - pysbd==0.3.4
      - pytesseract==0.3.10
      - python-docx==1.1.2
      - python-dotenv==1.0.1
      - python-iso639==2024.4.27
      - python-magic==0.4.27
      - python-multipart==0.0.20
      - python-oxmsg==0.0.1
      - python-pptx==0.6.23
      - pytz==2023.3.post1
      - rapidfuzz==3.9.4
      - referencing==0.35.1
      - regex==2023.6.3
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==13.7.1
      - rpds-py==0.18.1
      - rsa==4.9
      - ruff==0.4.10
      - sacremoses==0.1.1
      - safehttpx==0.1.6
      - safetensors==0.4.3
      - scikit-learn==1.3.0
      - scipy==1.11.2
      - semantic-version==2.10.0
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - setuptools==72.1.0
      - shellingham==1.5.4
      - sinling==0.3.6
      - sklearn-crfsuite==0.3.6
      - smart-open==6.3.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - sounddevice==0.5.0
      - soundfile==0.12.1
      - soupsieve==2.5
      - soxr==0.4.0
      - spacy==3.6.1
      - spacy-alignments==0.9.0
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.4
      - spacy-transformers==1.2.5
      - sqlalchemy==2.0.30
      - srsly==2.4.7
      - starlette==0.41.3
      - stdlib-list==0.9.0
      - streamlit==1.35.0
      - sudachidict-core==20240716
      - sudachipy==0.6.8
      - tabula-py==2.9.3
      - tabulate==0.9.0
      - tenacity==8.3.0
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - thinc==8.1.12
      - threadpoolctl==3.2.0
      - tiktoken==0.7.0
      - timm==1.0.7
      - tk==0.1.0
      - tokenizers==0.19.1
      - toml==0.10.2
      - tomlkit==0.12.0
      - toolz==0.12.1
      - tqdm==4.65.1
      - trainer==0.0.36
      - transformers==4.44.0
      - trash-cli==0.24.5.26
      - tts==0.22.0
      - typeguard==4.3.0
      - typer==0.12.3
      - typing-extensions==4.12.0
      - typing-inspect==0.9.0
      - tzdata==2023.3
      - tzlocal==5.2
      - ujson==5.10.0
      - umap-learn==0.5.6
      - unidecode==1.3.8
      - unstructured==0.14.10
      - unstructured-client==0.24.1
      - unstructured-inference==0.7.36
      - unstructured-pytesseract==0.3.12
      - urllib3==2.2.2
      - uvicorn==0.30.0
      - wasabi==1.1.2
      - watchdog==4.0.1
      - watchfiles==0.22.0
      - watermark==2.4.3
      - websocket-client==1.8.0
      - websockets==11.0.3
      - werkzeug==3.0.3
      - wheel==0.41.2
      - widgetsnbextension==4.0.8
      - wrapt==1.16.0
      - xlrd==2.0.1
      - xlsxwriter==3.2.0
      - yarl==1.9.4
      - zipp==3.20.0
      - zstandard==0.22.0
