nllb:
  model_config:
    translator_path: facebook/nllb-200-distilled-600M
    translitarator_path: facebook/nllb-200-distilled-600M
    torch_dtype: torch.float16
    low_cpu_mem_usage: True
    load_in_4bit: False
    load_in_8bit: False

m2m100:
  model_config:
    translator_path: facebook/m2m100_418M
    translitarator_path: facebook/m2m100_418M
    torch_dtype: torch.float16
    low_cpu_mem_usage: True
    load_in_4bit: False
    load_in_8bit: False

marian_mt:
  model_config:
    en_mul_translator_path: Helsinki-NLP/opus-mt-en-mul
    mul_en_translator_path: Helsinki-NLP/opus-mt-mul-en
    translitarator_path: facebook/m2m100_418M
    torch_dtype: torch.float16
    low_cpu_mem_usage: True
    load_in_4bit: False
    load_in_8bit: False
    device: cuda