hf:
  model_config:
    model_path: "microsoft/speecht5_tts"
    # model_path: "suno/bark-small"
    device: "cpu"
    torch_dtype: torch.float32
    low_cpu_mem_usage: True
  generation_config:
    forward_params:
      do_sample: True

coqui:
  model_config:
    model_path: "tts_models/en/ljspeech/vits"
    # model_path: "tts_models/en/vctk/vits"
    device: "cpu"
  generation_config:
    language: None
    speaker: None
    speaker_wav: None
    