NLLB_LANGUAGE_MAP_TRANSLATOR = {
    "Acehnese (Arabic)": "ace_Arab",
    "Acehnese (Latin)": "ace_Latn",
    "Mesopotamian Arabic": "acm_Arab",
    "Ta'izzi-Adeni Arabic": "acq_Arab",
    "Tunisian Arabic": "aeb_Arab",
    "Afrikaans": "afr_Latn",
    "South Levantine Arabic": "ajp_Arab",
    "Akan": "aka_Latn",
    "Amharic": "amh_Ethi",
    "North Levantine Arabic": "apc_Arab",
    "Arabic": "arb_Arab",
    "Modern Standard Arabic": "arb_Arab",
    "Modern Standard Arabic (Romanized)": "arb_Latn",
    "Najdi Arabic": "ars_Arab",
    "Moroccan Arabic": "ary_Arab",
    "Egyptian Arabic": "arz_Arab",
    "Assamese": "asm_Beng",
    "Asturian": "ast_Latn",
    "Awadhi": "awa_Deva",
    "Aymara": "ayr_Latn",
    "South Azerbaijani": "azb_Arab",
    "Azerbaijani": "azj_Latn",
    "Bashkir": "bak_Cyrl",
    "Bambara": "bam_Latn",
    "Balinese": "ban_Latn",
    "Belarusian": "bel_Cyrl",
    "Bemba": "bem_Latn",
    "Bengali": "ben_Beng",
    "Bhojpuri": "bho_Deva",
    "Banjar (Arabic)": "bjn_Arab",
    "Banjar (Latin)": "bjn_Latn",
    "Tibetan": "bod_Tibt",
    "Bosnian": "bos_Latn",
    "Buginese": "bug_Latn",
    "Bulgarian": "bul_Cyrl",
    "Catalan": "cat_Latn",
    "Cebuano": "ceb_Latn",
    "Czech": "ces_Latn",
    "Chokwe": "cjk_Latn",
    "Central Kurdish": "ckb_Arab",
    "Crimean Tatar": "crh_Latn",
    "Welsh": "cym_Latn",
    "Danish": "dan_Latn",
    "German": "deu_Latn",
    "Dinka": "dik_Latn",
    "Dyula": "dyu_Latn",
    "Dzongkha": "dzo_Tibt",
    "Greek": "ell_Grek",
    "English": "eng_Latn",
    "Esperanto": "epo_Latn",
    "Estonian": "est_Latn",
    "Basque": "eus_Latn",
    "Ewe": "ewe_Latn",
    "Faroese": "fao_Latn",
    "Fijian": "fij_Latn",
    "Finnish": "fin_Latn",
    "Fon": "fon_Latn",
    "French": "fra_Latn",
    "Friulian": "fur_Latn",
    "Nigerian Fulfulde": "fuv_Latn",
    "Scottish Gaelic": "gla_Latn",
    "Irish": "gle_Latn",
    "Galician": "glg_Latn",
    "Guarani": "grn_Latn",
    "Gujarati": "guj_Gujr",
    "Haitian Creole": "hat_Latn",
    "Hausa": "hau_Latn",
    "Hebrew": "heb_Hebr",
    "Hindi": "hin_Deva",
    "Chhattisgarhi": "hne_Deva",
    "Croatian": "hrv_Latn",
    "Hungarian": "hun_Latn",
    "Armenian": "hye_Armn",
    "Igbo": "ibo_Latn",
    "Ilocano": "ilo_Latn",
    "Indonesian": "ind_Latn",
    "Icelandic": "isl_Latn",
    "Italian": "ita_Latn",
    "Javanese": "jav_Latn",
    "Japanese": "jpn_Jpan",
    "Kabyle": "kab_Latn",
    "Kachin": "kac_Latn",
    "Kamba": "kam_Latn",
    "Kannada": "kan_Knda",
    "Kashmiri (Arabic)": "kas_Arab",
    "Kashmiri (Devanagari)": "kas_Deva",
    "Georgian": "kat_Geor",
    "Central Kanuri (Arabic)": "knc_Arab",
    "Central Kanuri (Latin)": "knc_Latn",
    "Kazakh": "kaz_Cyrl",
    "Kabiye": "kbp_Latn",
    "Kabuverdianu": "kea_Latn",
    "Khmer": "khm_Khmr",
    "Kikuyu": "kik_Latn",
    "Kinyarwanda": "kin_Latn",
    "Kyrgyz": "kir_Cyrl",
    "Kimbundu": "kmb_Latn",
    "Northern Kurdish": "kmr_Latn",
    "Kongo": "kon_Latn",
    "Korean": "kor_Hang",
    "Lao": "lao_Laoo",
    "Ligurian": "lij_Latn",
    "Limburgish": "lim_Latn",
    "Lingala": "lin_Latn",
    "Lithuanian": "lit_Latn",
    "Lombard": "lmo_Latn",
    "Latgalian": "ltg_Latn",
    "Luxembourgish": "ltz_Latn",
    "Luba-Kasai": "lua_Latn",
    "Ganda": "lug_Latn",
    "Luo": "luo_Latn",
    "Mizo": "lus_Latn",
    "Standard Latvian": "lvs_Latn",
    "Magahi": "mag_Deva",
    "Maithili": "mai_Deva",
    "Malayalam": "mal_Mlym",
    "Marathi": "mar_Deva",
    "Minangkabau (Arabic)": "min_Arab",
    "Minangkabau (Latin)": "min_Latn",
    "Macedonian": "mkd_Cyrl",
    "Plateau Malagasy": "plt_Latn",
    "Maltese": "mlt_Latn",
    "Manipuri": "mni_Beng",
    "Halh Mongolian": "khk_Cyrl",
    "Mossi": "mos_Latn",
    "Māori": "mri_Latn",
    "Burmese": "mya_Mymr",
    "Dutch": "nld_Latn",
    "Norwegian Nynorsk": "nno_Latn",
    "Norwegian Bokmål": "nob_Latn",
    "Nepali": "npi_Deva",
    "Northern Sotho": "nso_Latn",
    "Nuer": "nus_Latn",
    "Nyanja": "nya_Latn",
    "Occitan": "oci_Latn",
    "West Central Oromo": "gaz_Latn",
    "Odia": "ory_Orya",
    "Pangasinan": "pag_Latn",
    "Punjabi": "pan_Guru",
    "Papiamento": "pap_Latn",
    "Western Persian": "pes_Arab",
    "Polish": "pol_Latn",
    "Portuguese": "por_Latn",
    "Dari": "prs_Arab",
    "Southern Pashto": "pbt_Arab",
    "Ayacucho Quechua": "quy_Latn",
    "Romanian": "ron_Latn",
    "Rundi": "run_Latn",
    "Russian": "rus_Cyrl",
    "Sango": "sag_Latn",
    "Sanskrit": "san_Deva",
    "Santali (Ol Chiki)": "sat_Olck",
    "Sicilian": "scn_Latn",
    "Shan": "shn_Mymr",
    "Sinhala": "sin_Sinh",
    "Slovak": "slk_Latn",
    "Slovenian": "slv_Latn",
    "Samoan": "smo_Latn",
    "Shona": "sna_Latn",
    "Sindhi": "snd_Arab",
    "Somali": "som_Latn",
    "Southern Sotho": "sot_Latn",
    "Spanish": "spa_Latn",
    "Tosk Albanian": "als_Latn",
    "Sardinian": "srd_Latn",
    "Serbian": "srp_Cyrl",
    "Swati": "ssw_Latn",
    "Sundanese": "sun_Latn",
    "Swedish": "swe_Latn",
    "Swahili": "swh_Latn",
    "Silesian": "szl_Latn",
    "Tamil": "tam_Taml",
    "Tatar": "tat_Cyrl",
    "Telugu": "tel_Telu",
    "Tajik": "tgk_Cyrl",
    "Tagalog": "tgl_Latn",
    "Thai": "tha_Thai",
    "Tigrinya": "tir_Ethi",
    "Tamasheq (Latin)": "taq_Latn",
    "Tamasheq (Tifinagh)": "taq_Tfng",
    "Tok Pisin": "tpi_Latn",
    "Tswana": "tsn_Latn",
    "Tsonga": "tso_Latn",
    "Turkmen": "tuk_Latn",
    "Tumbuka": "tum_Latn",
    "Turkish": "tur_Latn",
    "Twi": "twi_Latn",
    "Central Atlas Tamazight": "tzm_Tfng",
    "Uyghur": "uig_Arab",
    "Ukrainian": "ukr_Cyrl",
    "Umbundu": "umb_Latn",
    "Urdu": "urd_Arab",
    "Northern Uzbek": "uzn_Latn",
    "Venetian": "vec_Latn",
    "Vietnamese": "vie_Latn",
    "Waray": "war_Latn",
    "Wolof": "wol_Latn",
    "Xhosa": "xho_Latn",
    "Yiddish": "ydd_Hebr",
    "Yoruba": "yor_Latn",
    "Cantonese": "yue_Hant",
    "Chinese": "zho_Hans",
    "Simplified Chinese": "zho_Hans",
    "Traditional Chinese": "zho_Hant",
    "Malay": "zsm_Latn",
    "Standard Malay": "zsm_Latn",
    "Zulu": "zul_Latn",
    "Zazaki": "diq_Latn",
    "Santali (Bengali)": "sat_Beng"
}

MARIAN_MT_LANGUAGE_MAP_TRANSLATOR = {
    'Abkhazian': 'abk',
    'Iraqi Arabic': 'acm',
    'Adyghe': 'ady',
    'Gulf Arabic': 'afb',
    'Afrihili (Latin script)': 'afh_Latn',
    'Afrikaans': 'afr',
    'Aklanon (Latin script)': 'akl_Latn',
    'Gheg Albanian': 'aln',
    'Amharic': 'amh',
    'Old English (Latin script)': 'ang_Latn',
    'North Levantine Arabic': 'apc',
    'Arabic': 'ara',
    'Aragonese': 'arg',
    'Algerian Arabic': 'arq',
    'Moroccan Arabic': 'ary',
    'Egyptian Arabic': 'arz',
    'Assamese': 'asm',
    'Asturian': 'ast',
    'Kotava (Latin script)': 'avk_Latn',
    'Awadhi': 'awa',
    'Azerbaijani (Latin script)': 'aze_Latn',
    'Bashkir': 'bak',
    'Bambara (Latin script)': 'bam_Latn',
    'Belarusian': 'bel',
    'Belarusian (Latin script)': 'bel_Latn',
    'Bengali': 'ben',
    'Bhojpuri': 'bho',
    'Tibetan': 'bod',
    'Bosnian (Latin script)': 'bos_Latn',
    'Breton': 'bre',
    'Bodo': 'brx',
    'Bodo (Latin script)': 'brx_Latn',
    'Bulgarian': 'bul',
    'Bulgarian (Latin script)': 'bul_Latn',
    'Catalan': 'cat',
    'Cebuano': 'ceb',
    'Czech': 'ces',
    'Chamorro': 'cha',
    'Chechen': 'che',
    'Cherokee': 'chr',
    'Chuvash': 'chv',
    'Jin Chinese (Simplified)': 'cjy_Hans',
    'Jin Chinese (Traditional)': 'cjy_Hant',
    'Mandarin Chinese': 'cmn',
    'Mandarin Chinese (Simplified)': 'cmn_Hans',
    'Mandarin Chinese (Traditional)': 'cmn_Hant',
    'Cornish': 'cor',
    'Corsican': 'cos',
    'Crimean Tatar': 'crh',
    'Crimean Tatar (Latin script)': 'crh_Latn',
    'Kashubian (Latin script)': 'csb_Latn',
    'Welsh': 'cym',
    'Danish': 'dan',
    'German': 'deu',
    'Lower Sorbian': 'dsb',
    'Central Dusun': 'dtp',
    'Dutton World Speedwords (Latin script)': 'dws_Latn',
    'Emilian': 'egl',
    'Greek': 'ell',
    'Middle English (Latin script)': 'enm_Latn',
    'Esperanto': 'epo',
    'Estonian': 'est',
    'Basque': 'eus',
    'Ewe': 'ewe',
    'Extremaduran': 'ext',
    'Faroese': 'fao',
    'Fijian': 'fij',
    'Finnish': 'fin',
    'Kven Finnish (Latin script)': 'fkv_Latn',
    'French': 'fra',
    'Middle French (Latin script)': 'frm_Latn',
    'Northern Frisian': 'frr',
    'Western Frisian': 'fry',
    'Pulaar': 'fuc',
    'Nigerian Fulfulde': 'fuv',
    'Gan Chinese': 'gan',
    'Guadeloupean Creole French (Latin script)': 'gcf_Latn',
    'Gilbertese': 'gil',
    'Scottish Gaelic': 'gla',
    'Irish': 'gle',
    'Galician': 'glg',
    'Manx': 'glv',
    'Goan Konkani': 'gom',
    'Gronings': 'gos',
    'Gothic (Gothic script)': 'got_Goth',
    'Ancient Greek (Greek script)': 'grc_Grek',
    'Guarani': 'grn',
    'Swiss German': 'gsw',
    'Gujarati': 'guj',
    'Haitian Creole': 'hat',
    'Hausa (Latin script)': 'hau_Latn',
    'Hawaiian': 'haw',
    'Hebrew': 'heb',
    'Fiji Hindi (Latin script)': 'hif_Latn',
    'Hiligaynon': 'hil',
    'Hindi': 'hin',
    'Hmong Njua (Latin script)': 'hnj_Latn',
    'Ho': 'hoc',
    'Ho (Latin script)': 'hoc_Latn',
    'Croatian': 'hrv',
    'Upper Sorbian': 'hsb',
    'Hungarian': 'hun',
    'Armenian': 'hye',
    'Iban': 'iba',
    'Igbo': 'ibo',
    'Ido': 'ido',
    'Ido (Latin script)': 'ido_Latn',
    'Eastern Canadian Inuktitut (Latin script)': 'ike_Latn',
    'Interlingue (Latin script)': 'ile_Latn',
    'Iloko': 'ilo',
    'Interlingua (Latin script)': 'ina_Latn',
    'Indonesian': 'ind',
    'Icelandic': 'isl',
    'Italian': 'ita',
    'Ingrian': 'izh',
    'Javanese': 'jav',
    'Javanese (Javanese script)': 'jav_Java',
    'Lojban': 'jbo',
    'Lojban (Cyrillic script)': 'jbo_Cyrl',
    'Lojban (Latin script)': 'jbo_Latn',
    'Juhuri (Cyrillic script)': 'jdt_Cyrl',
    'Japanese': 'jpn',
    'Kabyle': 'kab',
    'Kalaallisut': 'kal',
    'Kannada': 'kan',
    'Georgian': 'kat',
    'Kazakh (Cyrillic script)': 'kaz_Cyrl',
    'Kazakh (Latin script)': 'kaz_Latn',
    "Q'eqchi' (Latin script)": 'kek_Latn',
    'Khasi': 'kha',
    'Khmer': 'khm',
    'Khmer (Latin script)': 'khm_Latn',
    'Kinyarwanda': 'kin',
    'Kyrgyz (Cyrillic script)': 'kir_Cyrl',
    'Khakas': 'kjh',
    'Komi-Zyrian': 'kpv',
    'Karelian': 'krl',
    'Kölsch': 'ksh',
    'Kumyk': 'kum',
    'Kurdish (Arabic script)': 'kur_Arab',
    'Kurdish (Latin script)': 'kur_Latn',
    'Ladino': 'lad',
    'Ladino (Latin script)': 'lad_Latn',
    'Lao': 'lao',
    'Latin (Latin script)': 'lat_Latn',
    'Latvian': 'lav',
    'Láadan (Latin script)': 'ldn_Latn',
    'Lingua Franca Nova (Cyrillic script)': 'lfn_Cyrl',
    'Lingua Franca Nova (Latin script)': 'lfn_Latn',
    'Ligurian': 'lij',
    'Lingala': 'lin',
    'Lithuanian': 'lit',
    'Livonian (Latin script)': 'liv_Latn',
    'Lakota': 'lkt',
    'Ladin (Latin script)': 'lld_Latn',
    'Lombard': 'lmo',
    'Latgalian': 'ltg',
    'Luxembourgish': 'ltz',
    'Ganda': 'lug',
    'Literary Chinese': 'lzh',
    'Literary Chinese (Simplified)': 'lzh_Hans',
    'Madurese': 'mad',
    'Marshallese': 'mah',
    'Maithili': 'mai',
    'Malayalam': 'mal',
    'Marathi': 'mar',
    'North Moluccan Malay (Latin script)': 'max_Latn',
    'Moksha': 'mdf',
    'Morisyen': 'mfe',
    'Eastern Mari': 'mhr',
    "Mi'kmaq": 'mic',
    'Minangkabau': 'min',
    'Macedonian': 'mkd',
    'Malagasy': 'mlg',
    'Maltese': 'mlt',
    'Mon': 'mnw',
    'Mohawk': 'moh',
    'Mongolian': 'mon',
    'Māori': 'mri',
    'Mirandese': 'mwl',
    'Hmong Daw': 'mww',
    'Burmese': 'mya',
    'Erzya': 'myv',
    'Min Nan Chinese': 'nan',
    'Nauru': 'nau',
    'Navajo': 'nav',
    'Low German': 'nds',
    'Niuean': 'niu',
    'Dutch': 'nld',
    'Norwegian Nynorsk': 'nno',
    'Norwegian Bokmål': 'nob',
    'Norwegian Bokmål (Hebrew script)': 'nob_Hebr',
    'Nogai': 'nog',
    'Old Norse (Latin script)': 'non_Latn',
    'Novial (Latin script)': 'nov_Latn',
    'Nepali': 'npi',
    'Nyanja': 'nya',
    'Occitan': 'oci',
    'Odia': 'ori',
    'Old East Slavic (Cyrillic script)': 'orv_Cyrl',
    'Ossetian': 'oss',
    'Ottoman Turkish (Arabic script)': 'ota_Arab',
    'Ottoman Turkish (Latin script)': 'ota_Latn',
    'Pangasinan': 'pag',
    'Punjabi (Gurmukhi script)': 'pan_Guru',
    'Papiamento': 'pap',
    'Palauan': 'pau',
    'Pennsylvania German': 'pdc',
    'Iranian Persian': 'pes',
    'Iranian Persian (Latin script)': 'pes_Latn',
    'Iranian Persian (Thaana script)': 'pes_Thaa',
    'Piedmontese': 'pms',
    'Western Punjabi': 'pnb',
    'Polish': 'pol',
    'Portuguese': 'por',
    'Nahuat Pipil (Latin script)': 'ppl_Latn',
    'Prussian (Latin script)': 'prg_Latn',
    'Pashto': 'pus',
    "K'iche'": 'quc',
    'Quenya': 'qya',
    'Quenya (Latin script)': 'qya_Latn',
    'Rapa Nui': 'rap',
    'Riffian (Latin script)': 'rif_Latn',
    'Romansh': 'roh',
    'Romani': 'rom',
    'Romanian': 'ron',
    'Rusyn': 'rue',
    'Rundi': 'run',
    'Russian': 'rus',
    'Sango': 'sag',
    'Yakut': 'sah',
    'Sanskrit (Devanagari script)': 'san_Deva',
    'Sicilian': 'scn',
    'Scots': 'sco',
    'Samogitian': 'sgs',
    'Shuswap (Latin script)': 'shs_Latn',
    'Shawiya (Latin script)': 'shy_Latn',
    'Sinhala': 'sin',
    'Sindarin (Latin script)': 'sjn_Latn',
    'Slovenian': 'slv',
    'Southern Sami': 'sma',
    'Northern Sami': 'sme',
    'Samoan': 'smo',
    'Shona': 'sna',
    'Sindhi (Arabic script)': 'snd_Arab',
    'Somali': 'som',
    'Spanish': 'spa',
    'Albanian': 'sqi',
    'Serbian (Cyrillic script)': 'srp_Cyrl',
    'Serbian (Latin script)': 'srp_Latn',
    'Saterland Frisian': 'stq',
    'Sundanese': 'sun',
    'Swedish': 'swe',
    'Swabian': 'swg',
    'Swahili': 'swh',
    'Tahitian': 'tah',
    'Tamil': 'tam',
    'Tatar': 'tat',
    'Tatar (Arabic script)': 'tat_Arab',
    'Tatar (Latin script)': 'tat_Latn',
    'Telugu': 'tel',
    'Tetum': 'tet',
    'Tajik (Cyrillic script)': 'tgk_Cyrl',
    'Thai': 'tha',
    'Tigrinya': 'tir',
    'Klingon (Latin script)': 'tlh_Latn',
    'Talysh (Latin script)': 'tly_Latn',
    'Temuan (Latin script)': 'tmw_Latn',
    'Tonga (Latin script)': 'toi_Latn',
    'Tongan': 'ton',
    'Tupí (Latin script)': 'tpw_Latn',
    'Tsonga': 'tso',
    'Turkmen': 'tuk',
    'Turkmen (Latin script)': 'tuk_Latn',
    'Turkish': 'tur',
    'Tuvaluan': 'tvl',
    'Tuvinian': 'tyv',
    'Talossan': 'tzl',
    'Talossan (Latin script)': 'tzl_Latn',
    'Udmurt': 'udm',
    'Uyghur (Arabic script)': 'uig_Arab',
    'Uyghur (Cyrillic script)': 'uig_Cyrl',
    'Ukrainian': 'ukr',
    'Umbundu': 'umb',
    'Urdu': 'urd',
    'Uzbek (Cyrillic script)': 'uzb_Cyrl',
    'Uzbek (Latin script)': 'uzb_Latn',
    'Venetian': 'vec',
    'Vietnamese': 'vie',
    'Vietnamese (Han script)': 'vie_Hani',
    'Volapük (Latin script)': 'vol_Latn',
    'Võro': 'vro',
    'Waray': 'war',
    'Walloon': 'wln',
    'Wolof': 'wol',
    'Wu Chinese': 'wuu',
    'Kalmyk': 'xal',
    'Xhosa': 'xho',
    'Yiddish': 'yid',
    'Yoruba': 'yor',
    'Cantonese': 'yue',
    'Cantonese (Simplified)': 'yue_Hans',
    'Cantonese (Traditional)': 'yue_Hant',
    'Chinese': 'zho',
    'Chinese (Simplified)': 'zho_Hans',
    'Chinese (Traditional)': 'zho_Hant',
    'Malay': 'zlm_Latn',
    'Malay (Latin script)': 'zlm_Latn',
    'Standard Malay (Latin script)': 'zsm_Latn',
    'Zulu': 'zul',
    'Zaza': 'zza'
}

M2M100_LANGUAGE_MAP_TRANSLATOR = {
    'Afrikaans': 'af',
    'Amharic': 'am',
    'Arabic': 'ar',
    'Asturian': 'ast',
    'Azerbaijani': 'az',
    'Bashkir': 'ba',
    'Belarusian': 'be',
    'Bulgarian': 'bg',
    'Bengali': 'bn',
    'Breton': 'br',
    'Bosnian': 'bs',
    'Catalan': 'ca',
    'Cebuano': 'ceb',
    'Czech': 'cs',
    'Welsh': 'cy',
    'Danish': 'da',
    'German': 'de',
    'Greek': 'el',
    'English': 'en',
    'Spanish': 'es',
    'Estonian': 'et',
    'Persian': 'fa',
    'Fulah': 'ff',
    'Finnish': 'fi',
    'French': 'fr',
    'Western Frisian': 'fy',
    'Irish': 'ga',
    'Scottish Gaelic': 'gd',
    'Galician': 'gl',
    'Gujarati': 'gu',
    'Hausa': 'ha',
    'Hebrew': 'he',
    'Hindi': 'hi',
    'Croatian': 'hr',
    'Haitian Creole': 'ht',
    'Hungarian': 'hu',
    'Armenian': 'hy',
    'Indonesian': 'id',
    'Igbo': 'ig',
    'Iloko': 'ilo',
    'Icelandic': 'is',
    'Italian': 'it',
    'Japanese': 'ja',
    'Javanese': 'jv',
    'Georgian': 'ka',
    'Kazakh': 'kk',
    'Khmer': 'km',
    'Kannada': 'kn',
    'Korean': 'ko',
    'Luxembourgish': 'lb',
    'Ganda': 'lg',
    'Lingala': 'ln',
    'Lao': 'lo',
    'Lithuanian': 'lt',
    'Latvian': 'lv',
    'Malagasy': 'mg',
    'Macedonian': 'mk',
    'Malayalam': 'ml',
    'Mongolian': 'mn',
    'Marathi': 'mr',
    'Malay': 'ms',
    'Burmese': 'my',
    'Nepali': 'ne',
    'Dutch': 'nl',
    'Norwegian': 'no',
    'Northern Sotho': 'ns',
    'Occitan': 'oc',
    'Oriya': 'or',
    'Punjabi': 'pa',
    'Polish': 'pl',
    'Pashto': 'ps',
    'Portuguese': 'pt',
    'Romanian': 'ro',
    'Russian': 'ru',
    'Sindhi': 'sd',
    'Sinhala': 'si',
    'Slovak': 'sk',
    'Slovenian': 'sl',
    'Somali': 'so',
    'Albanian': 'sq',
    'Serbian': 'sr',
    'Swati': 'ss',
    'Sundanese': 'su',
    'Swedish': 'sv',
    'Swahili': 'sw',
    'Tamil': 'ta',
    'Thai': 'th',
    'Tagalog': 'tl',
    'Tswana': 'tn',
    'Turkish': 'tr',
    'Ukrainian': 'uk',
    'Urdu': 'ur',
    'Uzbek': 'uz',
    'Vietnamese': 'vi',
    'Wolof': 'wo',
    'Xhosa': 'xh',
    'Yiddish': 'yi',
    'Yoruba': 'yo',
    'Chinese': 'zh',
    'Zulu': 'zu'
}